CREATE SCHEMA ESTOQUE;

USE ESTOQUE;

CREATE TABLE usr_usuario (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  PRIMARY KEY (USR_ID),
  UNIQUE KEY UNI_USUARIO_NOME (USR_NOME)
);

CREATE TABLE aut_autorizacao (
  AUT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUT_NOME VARCHAR(20) NOT NULL,
  PRIMARY KEY (AUT_ID),
  UNIQUE KEY UNI_AUT_NOME (AUT_NOME)
);

CREATE TABLE uau_usuario_autorizacao (
  USR_ID BIGINT UNSIGNED NOT NULL,
  AUT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (USR_ID, AUT_ID),
  FOREIGN KEY AUT_USUARIO_FK (USR_ID) REFERENCES USR_USUARIO (USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY AUT_AUTORIZACAO_FK (AUT_ID) REFERENCES AUT_AUTORIZACAO (AUT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ant_anotacao (
  ANT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ANT_ASSUNTO VARCHAR(100) NOT NULL,
  ANT_TEXTO VARCHAR(500) NOT NULL,
  ANT_DATA_HORA DATETIME NOT NULL,
  USR_CRIACAO_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (ANT_ID),
  FOREIGN KEY ANT_USR_FK (USR_CRIACAO_ID) REFERENCES USR_USUARIO(USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE bico (
	id_bico BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(20) NOT NULL,
	pagamento VARCHAR(128),
	descricao VARCHAR(512),
  usr_bico_id BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (id_bico),
	FOREIGN KEY bico_user_fk (usr_bico_id) REFERENCES usr_usuario(USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO usr_usuario(USR_NOME, USR_SENHA) VALUES('teste', CONCAT('{MD5}', MD5('teste')));
INSERT INTO usr_usuario(USR_NOME, USR_SENHA) VALUES('admin', CONCAT('{MD5}', MD5('admin')));
INSERT INTO aut_autorizacao(AUT_NOME) VALUES('ROLE_USUARIO');
INSERT INTO aut_autorizacao(AUT_NOME) VALUES('ROLE_ADMIN');
INSERT INTO uau_usuario_autorizacao(USR_ID, AUT_ID)
SELECT USR_ID, AUT_ID
FROM usr_usuario, aut_autorizacao
WHERE USR_NOME = 'teste'
AND AUT_NOME = 'ROLE_USUARIO';
INSERT INTO UAU_USUARIO_AUTORIZACAO(USR_ID, AUT_ID)
SELECT USR_ID, AUT_ID
FROM usr_usuario, aut_autorizacao
WHERE USR_NOME = 'admin';